//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by in_cwave.rc
//
#define IDD_INFO                        102
#define IDD_ADV_SETUP                   103
#define IDD_NEW_DSP                     104
#define IDD_SYSETUP                     105
#define IDD_GETVALUE                    106
#define IDS_GAIN                        1005
#define IDC_SHOWPLAY                    1014
#define IDL_INFO                        1015
#define IDB_CHECK                       1016
#define IDC_API_TOGGLE                  1021
#define IDL_DSP                         1022
#define IDB_ADD                         1023
#define IDB_SAVE                        1024
#define IDB_DEL                         1025
#define IDB_DELALL                      1026
#define IDB_LOAD                        1027
#define IDC_IN0                         1028
#define IDC_INA                         1029
#define IDC_INB                         1030
#define IDC_INC                         1031
#define IDC_IND                         1032
#define IDC_INE                         1033
#define IDC_INF                         1034
#define IDC_ING                         1035
#define IDC_INH                         1036
#define IDC_INI                         1037
#define IDC_INJ                         1038
#define IDC_INK                         1039
#define IDC_INL                         1040
#define IDC_INM                         1041
#define IDC_INN                         1042
#define IDC_INO                         1043
#define IDC_INP                         1044
#define IDC_INQ                         1045
#define IDC_INR                         1046
#define IDC_INS                         1047
#define IDC_INT                         1048
#define IDC_INU                         1049
#define IDC_INV                         1050
#define IDC_INW                         1051
#define IDC_INX                         1052
#define IDC_INY                         1053
#define IDC_INZ                         1054
#define IDC_OUTA                        1055
#define IDC_OUTB                        1056
#define IDC_OUTC                        1057
#define IDC_OUTD                        1058
#define IDC_OUTE                        1059
#define IDC_OUTF                        1060
#define IDC_OUTG                        1061
#define IDC_OUTH                        1062
#define IDC_OUTI                        1063
#define IDC_OUTJ                        1064
#define IDC_OUTK                        1065
#define IDC_OUTL                        1066
#define IDC_OUTM                        1067
#define IDC_OUTN                        1068
#define IDC_OUTO                        1069
#define IDC_OUTP                        1070
#define IDC_OUTQ                        1071
#define IDC_OUTR                        1072
#define IDC_OUTS                        1073
#define IDC_OUTT                        1074
#define IDC_OUTU                        1075
#define IDC_OUTV                        1076
#define IDC_OUTW                        1077
#define IDC_OUTX                        1078
#define IDC_OUTY                        1079
#define IDC_OUTZ                        1080
#define IDC_GAINL                       1081
#define IDC_GAINR                       1082
#define IDC_GAIN_LOCK                   1083
#define IDC_FSHIFTL                     1084
#define IDC_FSHIFTR                     1085
#define IDC_FSHIFT_LOCK                 1086
#define IDC_FSHIFTL_BYPASS              1087
#define IDC_FSHIFTR_BYPASS              1088
#define IDC_PMFRL                       1089
#define IDC_PML_BYPASS                  1090
#define IDC_PMFRR                       1091
#define IDC_PMR_BYPASS                  1092
#define IDC_PMFR_LOCK                   1093
#define IDC_PMLEVL                      1094
#define IDC_PMLEVR                      1095
#define IDC_PMLEV_LOCK                  1096
#define IDC_PMANGL                      1097
#define IDC_PMANGR                      1098
#define IDC_PMANG_LOCK                  1099
#define IDS_FSHIFT                      1100
#define IDS_PMFR                        1101
#define IDS_PMLEV                       1102
#define IDS_PMANG                       1103
#define IDC_ML_ADD_REIM                 1104
#define IDC_ML_SUB_REIM                 1105
#define IDC_ML_RE                       1106
#define IDC_ML_IM                       1107
#define IDC_MR_ADD_REIM                 1108
#define IDC_MR_SUB_REIM                 1109
#define IDC_MR_RE                       1110
#define IDC_MR_IM                       1111
#define IDB_RESET_CLIPS                 1112
#define IDS_CLIPSL                      1113
#define IDS_CLIPSR                      1114
#define IDS_OUTPUTS                     1115
#define IDC_NAME                        1116
#define IDS_PMIPH                       1117
#define IDC_TYPE_SHIFT                  1118
#define IDC_TYPE_PM                     1119
#define IDC_TYPE_MIX                    1120
#define IDC_PMIPHL                      1121
#define IDC_PMIPHR                      1122
#define IDC_PMIPH_LOCK                  1123
#define IDC_ADV24BITS                   1124
#define IDS_NFR_PLAY                    1125
#define IDS_NFR_TRANS                   1126
#define IDB_RESET_NFR_PLAY              1127
#define IDB_RESET_NFR_TRANS             1128
#define IDB_RESET_HILB_PLAY             1129
#define IDB_RESET_HILB_TRANS            1130
#define IDL_EHILBERT                    1131
#define IDL_RENDER                      1132
#define IDC_DTH_BITS                    1133
#define IDB_DTH_BITS                    1134
#define IDB_SYSETUP                     1135
#define IDL_NOISE_SHAPING               1136
#define IDC_WAVEXT                      1137
#define IDS_RJ_PLAY                     1138
#define IDB_QUANTIZE                    1139
#define IDC_RWAVEEXT                    1140
#define IDS_RJ_TRANS                    1141
#define IDS_LH_SN                       1142
#define IDC_PAR_NOPARENT                1143
#define IDC_PAR_FILELIST                1144
#define IDC_PAR_MAINWND                 1145
#define IDS_LH_TOT                      1146
#define IDS_LH_NI                       1147
#define IDS_LH_ND                       1148
#define IDC_LAST_CHANCE                 1149
#define IDS_LH_PD                       1150
#define IDC_SLEEPTIME                   1151
#define IDS_LH_PI                       1152
#define IDB_SLEEPTIME                   1153
#define IDC_NOSLEEP                     1154
#define IDB_LH_RES                      1155
#define IDC_XCH_LR                      1156
#define IDC_XCH_RL                      1157
#define IDC_XCH_LL                      1158
#define IDC_XCH_RR                      1159
#define IDC_XCH_MIX                     1160
#define IDB_XIQL                        1161
#define IDB_XIQR                        1162
#define IDB_GAINL                       1163
#define IDC_GETVALUE                    1164
#define IDB_GAINR                       1165
#define IDS_GETVALUE                    1166
#define IDB_FSHIFTL                     1167
#define IDB_FSHIFTR                     1168
#define IDB_PMFRL                       1169
#define IDB_PMFRR                       1170
#define IDB_PMIPHL                      1171
#define IDB_PMIPHR                      1172
#define IDB_PMLEVL                      1173
#define IDB_PMLEVR                      1174
#define IDB_PMANGL                      1175
#define IDB_PMANGR                      1176
#define IDC_LONG_NO                     1177
#define IDC_MODFR_SCALED                1178
#define IDC_MODFR_NATIVE                1179
#define IDC_SEXCP                       1180
#define IDS_LS_PI                       1181
#define IDB_LS_RES                      1182
#define IDS_LS_SN                       1183
#define IDS_LS_QN                       1184
#define IDS_LS_NI                       1185
#define IDS_LS_ND                       1186
#define IDS_LS_PD                       1187
#define IDS_RH_ND                       1188
#define IDS_RH_PD                       1189
#define IDS_RH_PI                       1190
#define IDB_RH_RES                      1191
#define IDS_RS_PI                       1192
#define IDB_RS_RES                      1193
#define IDS_RS_SN                       1194
#define IDS_RS_QN                       1195
#define IDS_RS_NI                       1196
#define IDS_RS_ND                       1197
#define IDS_RS_PD                       1198
#define IDS_RH_SN                       1199
#define IDS_RH_QN                       1200
#define IDS_RH_NI                       1201
#define IDS_LH_QN                       1202
#define IDB_FPALL_RES                   1203
#define IDS_LS_TOT                      1204
#define IDS_RH_TOT                      1205
#define IDS_RS_TOT                      1206
#define IDC_BYPASS_LIST                 1207
#define IDC_RESET_NFR                   1208
#define IDC_RESET_HILB                  1209
#define IDC_ALIGN                       1210
#define IDC_FADE_IN                     1211
#define IDC_FADE_OUT                    1212
#define IDB_TRACCEPT                    1213
#define IDC_KAHAN_SUM                   1214
#define IDC_SUB_THR                     1215
#define IDB_SUB_THR                     1216
#define IDC_RJ_SUB_THR                  1217
#define IDB_RESET_RJ_PLAY               1218
#define IDB_RESET_RJ_TRANS              1219
#define IDC_SIGNBITS_16                 1220
#define IDS_SIGNBITS_16                 1221
#define IDC_SIGNBITS_24                 1222
#define IDS_SIGNBITS_24                 1223

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1224
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
